import React, { useState, useEffect } from 'react';
import { LayoutDashboard, Users, Settings, Play, Pause, Activity } from 'lucide-react';
import axios from 'axios';

// --- Generated by Stitch (Design) & Wired by Jules (Logic) ---

const API_URL = "http://localhost:8001";

export default function App() {
  const [stats, setStats] = useState({ new: 0, contacted: 0, won: 0 });
  const [nurtureActive, setNurtureActive] = useState(true);

  useEffect(() => {
    const poll = setInterval(async () => {
      try {
        const res = await axios.get(`${API_URL}/stats`);
        setStats(res.data);
        const toggle = await axios.get(`${API_URL}/control/nurture`);
        setNurtureActive(toggle.data.active);
      } catch (e) { console.error("Sync failed"); }
    }, 2000);
    return () => clearInterval(poll);
  }, []);

  const toggleNurture = async () => {
    await axios.post(`${API_URL}/control/nurture`, { active: !nurtureActive });
    setNurtureActive(!nurtureActive);
  };

  return (
    <div className="flex h-screen bg-gray-50 font-sans text-gray-900">
      {/* Sidebar */}
      <aside className="w-64 bg-white border-r border-gray-200 p-6 flex flex-col">
        <div className="flex items-center gap-2 mb-10 text-indigo-600">
          <LayoutDashboard size={28} />
          <span className="text-xl font-bold tracking-tight">HighEncode</span>
        </div>
        <nav className="space-y-2 flex-1">
          <NavItem icon={<Users />} label="Leads" active />
          <NavItem icon={<Activity />} label="Campaigns" />
          <NavItem icon={<Settings />} label="Settings" />
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-10 overflow-auto">
        <header className="flex justify-between items-center mb-10">
          <div>
            <h1 className="text-3xl font-bold">Pipeline Overview</h1>
            <p className="text-gray-500 mt-1">Real-time automation status</p>
          </div>
          <button 
            onClick={toggleNurture}
            className={`flex items-center gap-2 px-5 py-2.5 rounded-full font-medium transition-all ${
              nurtureActive 
                ? 'bg-green-100 text-green-700 hover:bg-green-200' 
                : 'bg-amber-100 text-amber-700 hover:bg-amber-200'
            }`}
          >
            {nurtureActive ? <Pause size={18} /> : <Play size={18} />}
            {nurtureActive ? 'Pause Nurture' : 'Resume Nurture'}
          </button>
        </header>

        {/* Stats Grid */}
        <div className="grid grid-cols-3 gap-6 mb-10">
          <StatCard label="New Leads" value={stats.new} color="bg-blue-500" />
          <StatCard label="Contacted" value={stats.contacted} color="bg-purple-500" />
          <StatCard label="Won Deals" value={stats.won} color="bg-emerald-500" />
        </div>

        {/* Placeholder for List */}
        <div className="bg-white rounded-2xl border border-gray-100 p-8 shadow-sm h-96 flex items-center justify-center text-gray-400">
          <p>Recent activity log would go here...</p>
        </div>
      </main>
    </div>
  );
}

function NavItem({ icon, label, active }) {
  return (
    <div className={`flex items-center gap-3 px-4 py-3 rounded-xl cursor-pointer transition-colors ${
      active ? 'bg-indigo-50 text-indigo-700' : 'text-gray-500 hover:bg-gray-50'
    }`}>
      {icon}
      <span className="font-medium">{label}</span>
    </div>
  );
}

function StatCard({ label, value, color }) {
  return (
    <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm relative overflow-hidden group hover:shadow-md transition-shadow">
      <div className={`absolute top-0 left-0 w-1 h-full ${color}`}></div>
      <p className="text-gray-500 font-medium mb-2">{label}</p>
      <p className="text-4xl font-bold text-gray-900">{value}</p>
    </div>
  );
}
